### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by rynProject** [julianvasa/ionic5-wordpress-app#2]
npm install https://github.com/julianvasa/ionic4-wordpress-app
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "unegatuaj" under a package
npm ERR! also called "unegatuaj". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/brgx21guns/.npm/_logs/2019-06-25T19_19_18_613Z-debug.log

**Comment by julianvasa** [comment]
I change project name. Please try again

**Comment by kosukeueki** [comment]
so, i have to change the project name to?

**Comment by rynProject** [comment]
same just the package changed

npm install https://github.com/julianvasa/ionic4-wordpress-app
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "ionic-wp-app" under a package
npm ERR! also called "ionic-wp-app". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/brgx21guns/.npm/_logs/2019-06-25T20_24_59_964Z-debug.log

**Comment by julianvasa** [comment]
No, you should not change anything. Can you try with the following steps?
1. git clone https://github.com/julianvasa/ionic4-wordpress-app
2. cd directory
3. npm install
